swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /draw/{id}:
    delete:
      tags:
      - draw
      description: delete the Draw
      operationId: DrawController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
  /draw/Edit:
    put:
      tags:
      - draw
      description: update the Draw
      operationId: DrawController.Put
      parameters:
      - in: formData
        name: id
        description: The id you want to update
        required: true
        type: integer
        format: int64
      - in: formData
        name: title
        description: body for Draw content
        required: true
        type: string
      - in: formData
        name: intro
        description: body for Draw content
        required: true
        type: string
      - in: formData
        name: type
        description: body for Draw content
        required: true
        type: integer
        format: int64
      - in: formData
        name: times
        description: body for Draw content
        required: true
        type: integer
        format: int64
      - in: formData
        name: showResult
        description: body for Draw content
        required: true
        type: integer
        format: int64
      - in: formData
        name: showRate
        description: body for Draw content
        required: true
        type: integer
        format: int64
      - in: formData
        name: showType
        description: body for Draw content
        required: true
        type: integer
        format: int64
      - in: formData
        name: condition
        description: body for Draw content
        required: true
        type: integer
        format: int64
      - in: formData
        name: joinNum
        description: body for Draw content
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Draw'
        "403":
          description: :id is not int
  /draw/GetAll:
    get:
      tags:
      - draw
      description: get Draw
      operationId: DrawController.GetAll
      parameters:
      - in: header
        name: token
        description: 登录凭证
        required: true
        type: string
      - in: query
        name: num
        description: 每页显示数
        type: integer
        format: int64
      - in: query
        name: page
        description: 页数
        type: integer
        format: int64
      - in: query
        name: title
        description: 标题
        type: string
      - in: query
        name: status
        description: 状态
        type: integer
        format: int64
      - in: query
        name: sTime
        description: 起始时间
        type: string
      - in: query
        name: eTime
        description: 结束时间
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Draw'
        "403":
          description: ""
  /draw/GetDrawContent:
    get:
      tags:
      - draw
      description: get Draw by id
      operationId: DrawController.GetOne
      parameters:
      - in: header
        name: token
        description: The key for staticblock
        required: true
        type: string
      - in: query
        name: id
        description: The key for staticblock
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Draw'
        "403":
          description: :id is empty
  /draw/GetDrawInfo:
    get:
      tags:
      - draw
      description: get Draw by id
      operationId: DrawController.getDrawInfo
      parameters:
      - in: query
        name: id
        description: The key for staticblock
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Draw'
        "403":
          description: id is empty
  /draw/Login:
    post:
      tags:
      - draw
      description: delete the Draw
      operationId: DrawController.Login
      parameters:
      - in: formData
        name: phone
        description: The id you want to delete
        required: true
        type: integer
        format: int64
      - in: formData
        name: password
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string}'
        "403":
          description: id is empty
  /draw/SaveConfig:
    post:
      tags:
      - draw
      description: create Draw
      operationId: DrawController.Create
      parameters:
      - in: header
        name: token
        description: 登录凭证
        required: true
        type: string
      - in: formData
        name: id
        description: body for Draw content
        type: integer
        format: int64
      - in: formData
        name: title
        description: body for Draw content
        required: true
        type: string
      - in: formData
        name: intro
        description: body for Draw content
        required: true
        type: string
      - in: formData
        name: type
        description: body for Draw content
        required: true
        type: integer
        format: int64
      - in: formData
        name: times
        description: body for Draw content
        required: true
        type: integer
        format: int64
      - in: formData
        name: showResult
        description: body for Draw content
        required: true
        type: integer
        format: int64
      - in: formData
        name: showRate
        description: body for Draw content
        required: true
        type: integer
        format: int64
      - in: formData
        name: showType
        description: body for Draw content
        required: true
        type: integer
        format: int64
      - in: formData
        name: condition
        description: body for Draw content
        required: true
        type: integer
        format: int64
      - in: formData
        name: joinNum
        description: body for Draw content
        required: true
        type: integer
        format: int64
      - in: formData
        name: prizeConfigs
        description: body for Draw content
        type: string
      - in: formData
        name: playConfigs
        description: body for Draw content
        type: string
      responses:
        "201":
          description: ""
          schema:
            $ref: '#/definitions/models.Draw'
        "403":
          description: body is empty
  /drawResult/ExportDrawInfo:
    get:
      tags:
      - drawResult
  /drawResult/GetInfo:
    get:
      tags:
      - drawResult
      description: get Draw by id
      operationId: DrawResultController.GetInfo
      parameters:
      - in: header
        name: token
        description: The key for staticblock
        required: true
        type: string
      - in: query
        name: id
        description: The key for staticblock
        required: true
        type: integer
        format: int64
      - in: query
        name: userNick
        description: The key for staticblock
        type: string
      - in: query
        name: prizeName
        description: The key for staticblock
        type: string
      - in: query
        name: phone
        description: The key for staticblock
        type: string
      - in: query
        name: isPrize
        description: The key for staticblock
        type: integer
        format: int64
      - in: query
        name: sTime
        description: The key for staticblock
        type: integer
        format: int64
      - in: query
        name: eTime
        description: The key for staticblock
        type: integer
        format: int64
      responses:
        "403":
          description: id is empty
  /drawResult/PersonResult:
    get:
      tags:
      - drawResult
      description: get Draw by id
      operationId: DrawResultController.personResult
      parameters:
      - in: query
        name: userId
        description: The key for staticblock
        required: true
        type: integer
        format: int64
      - in: query
        name: id
        description: The key for staticblock
        required: true
        type: integer
        format: int64
      responses:
        "403":
          description: id is empty
  /drawResult/WriteOff:
    post:
      tags:
      - drawResult
      description: WriteOff
      operationId: DrawResultController.WriteOff
      parameters:
      - in: header
        name: token
        description: The key for staticblock
        required: true
        type: string
      - in: formData
        name: recordId
        description: The key for staticblock
        required: true
        type: integer
        format: int64
      - in: formData
        name: userNick
        description: The key for staticblock
        type: string
      responses:
        "403":
          description: id is empty
definitions:
  models.Draw:
    title: Draw
    type: object
    properties:
      aid:
        type: integer
        format: int64
      condition:
        type: integer
        format: int64
      countDown:
        type: integer
        format: int64
      createTime:
        type: integer
        format: int64
      endTime:
        type: integer
        format: int64
      id:
        type: integer
        format: int64
      intro:
        type: string
      joinNum:
        type: integer
        format: int64
      nowPlay:
        type: integer
        format: int64
      playConfigs:
        type: array
        items:
          $ref: '#/definitions/models.DrawPlay'
      previewUrl:
        type: string
      prizeConfigs:
        type: array
        items:
          $ref: '#/definitions/models.DrawPrize'
      showRate:
        type: integer
        format: int64
      showResult:
        type: integer
        format: int64
      showType:
        type: integer
        format: int64
      startTime:
        type: integer
        format: int64
      status:
        type: integer
        format: int64
      times:
        type: integer
        format: int64
      title:
        type: string
      totalPlay:
        type: integer
        format: int64
      type:
        type: integer
        format: int64
      uin:
        type: integer
        format: int64
  models.DrawPlay:
    title: DrawPlay
    type: object
    properties:
      deleted:
        type: integer
        format: int64
      drawId:
        type: integer
        format: int64
      endTime:
        type: integer
        format: int64
      id:
        type: integer
        format: int64
      play:
        type: integer
        format: int64
      startTime:
        type: integer
        format: int64
  models.DrawPrize:
    title: DrawPrize
    type: object
    properties:
      createTime:
        type: integer
        format: int64
      deleted:
        type: integer
        format: int64
      drawId:
        type: integer
        format: int64
      icon:
        type: string
      id:
        type: integer
        format: int64
      level:
        type: integer
        format: int64
      name:
        type: string
      num:
        type: integer
        format: int64
      prizeAlias:
        type: string
      sum:
        type: integer
        format: int64
      type:
        type: integer
        format: int64
      typeInfo:
        type: string
      winningRate:
        type: integer
        format: int64
tags:
- name: draw
  description: |
    DrawController operations for Draw
- name: drawResult
  description: |
    DrawController operations for Draw
